version: '3.8'

services:
  nextjs-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:3322
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production,
      VAPID_PUBLIC_KEY: your-public-key
      VAPID_PRIVATE_KEY: your-private-key
      
    ports:
      - "3322:3322"
